use_sim_time: false
odom_frame: odom
map_frame: map
base_frame: base_link
scan_topic: scan
mode: mapping
resolution: 0.05
max_laser_range: 8.0
minimum_time_interval: 0.5
transform_publish_period: 0.05
publish_tf: true
