<?xml version="1.0"?>
<robot name="yahboomcar_X3" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 기본 파라미터 -->
  <xacro:property name="wheel_separation" value="0.30"/>   <!-- 좌우 바퀴 간 거리 -->
  <xacro:property name="wheel_radius" value="0.05"/>       <!-- 바퀴 반지름 -->
  <xacro:property name="wheel_thickness" value="0.02"/>    <!-- 바퀴 두께 -->
  <xacro:property name="base_size_x" value="0.3"/>         <!-- 베이스 길이 -->
  <xacro:property name="base_size_y" value="0.2"/>         <!-- 베이스 폭 -->
  <xacro:property name="base_size_z" value="0.1"/>         <!-- 베이스 높이 -->

  <!-- 재질 -->
  <material name="Green"><color rgba="0 1 0 1"/></material>
  <material name="Black"><color rgba="0 0 0 1"/></material>
  <material name="Gray"><color rgba="0.5 0.5 0.5 1"/></material>

  <!-- ===== Base link ===== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_size_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_size_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!-- ===== Wheels ===== -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 바퀴 4개 배치 -->
  <xacro:wheel name="front_left_wheel"  x="${ base_size_x/2 }"  y="${ wheel_separation/2 }"/>
  <xacro:wheel name="front_right_wheel" x="${ base_size_x/2 }"  y="-${ wheel_separation/2 }"/>
  <xacro:wheel name="rear_left_wheel"   x="-${ base_size_x/2 }" y="${ wheel_separation/2 }"/>
  <xacro:wheel name="rear_right_wheel"  x="-${ base_size_x/2 }" y="-${ wheel_separation/2 }"/>

</robot>
