scan_manager:
  ros__parameters:
    map_frame: "map"
    goal_topic: "/goal_pose"
    balls_topic: "/balls"
    spin_speed: 0.3
    spin_rounds: 2
    settle_sec: 1.0

    # 리스트 대신 prefix 기반 key로 명시
    waypoints.wp1.x: 0.0
    waypoints.wp1.y: 0.0
    waypoints.wp1.yaw_deg: 0.0

    waypoints.wp2.x: 3.0
    waypoints.wp2.y: 0.0
    waypoints.wp2.yaw_deg: 0.0

    waypoints.wp3.x: 3.0
    waypoints.wp3.y: 6.0
    waypoints.wp3.yaw_deg: 180.0

    waypoints.wp4.x: 0.0
    waypoints.wp4.y: 6.0
    waypoints.wp4.yaw_deg: 180.0

    waypoints.wp5.x: 1.5
    waypoints.wp5.y: 3.0
    waypoints.wp5.yaw_deg: 90.0
