topics:
  - name: e_stop
    topic: /safety/estop_cmd
    timeout: 0.5
    priority: 100
  - name: servo
    topic: /cmd_vel_servo
    timeout: 0.2
    priority: 70
  - name: nav2
    topic: /nav2/cmd_vel
    timeout: 0.2
    priority: 60
output_topic: /cmd_vel_out
