/**:
  ros__parameters:
    output_topic: /cmd_vel
    topics:
      servo:    { topic: /cmd_vel_servo,    timeout: 0.5, priority: 100 }
      nav2:     { topic: /cmd_vel_nav2,     timeout: 0.5, priority: 50  }

